kind: Deployment
apiVersion: apps/v1
metadata:
  name: demodeploy
spec:
  replicas: 5
  selector:
    matchLabels:
      app: monfront
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  minReadySeconds: 10
  template:
    metadata:
      labels:
        app: monfront
    spec:
      containers:
      - image: nginx:1.18  # suivante 1.19
        imagePullPolicy: Always
        name: podfront
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
