kind: Pod
apiVersion: v1
metadata:
  name: demopodwithsecretconfigmapenv
spec:
  containers:
  - name: podnginxwithsecretconfigmapenv
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: monstorage
    env:
      - name: DNNAME
        valueFrom:
          configMapKeyRef:
            name: db-config
            key: dbName
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: db-secret
            key: username
  volumes:
  - name: monstorage
    configMap:
      name: config
