apiVersion: v1
kind: Pod
metadata:
  name: demohostpath
spec:
  containers:
  - name: hostpathnginx
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - mountPath: /usr/share/nginx/html
      name: hostpathvolume
    - mountPath: /usr/toto
      name: hostpathvolume
  volumes:
  - name: hostpathvolume
    hostPath:
      path: /demo/data
      type: Directory
