apiVersion: v1
kind: Service
metadata:
  name: demo-servicenp
spec:
  type: NodePort
  selector:
    app: monfront
  ports:
    - port: 80            # Port sur lequel le service écoute
      targetPort: 80      # Port sur lequel le pod écoute
      protocol: TCP        # Protocole à utiliser
      nodePort: 30000      # Port externe (vous pouvez le changer si besoin)
